apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- template "labels" .}}
  name: {{.Release.Name}}{{.Values.metadata.name}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: bakehouse
  template:
    metadata:
      labels:   
        app: bakehouse
    spec:
      containers:
      - image: kareemelkasaby/vfbakehouse:36
        name: {{.Values.metadata.name}}
        imagePullPolicy: Always
        ports:
        - containerPort: {{.Values.service.port}}
        resources: {}
