apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: agent-app-iti
  name: agent-app-iti
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-app
  template:
    metadata:
      labels:
        app: agent-app
    spec:
      containers:
      - image: moelzedy/iti-bakehouse-jenkins-proj:${BUILD_NUMBER}
        name: agent-app-iti
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources: {}
