
apiVersion: v1
kind: Service
metadata:
  labels:
    app: agent-app-iti
  name: my-agent-svg
spec:
  ports:
  - name: myagentport
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30010
  selector:
    app: agent-app-iti
  type: NodePort
status:
  loadBalancer: {}
